version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: jin-gateway
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./conf.d:/etc/nginx/conf.d:ro
            - /srv/ssl:/etc/nginx/ssl:ro
        networks:
            - jin-proxy
        restart: unless-stopped

networks:
    jin-proxy:
        driver: bridge
