services:
    ray-auto-deploy-server:
        image: ray-auto-deploy-server
        container_name: ray-auto-deploy-server
        env_file:
            - /srv/env/ray-auto-deploy-server/.env
        volumes:
            - /srv/env/ray-auto-deploy-server/ray.config.json:/app/ray.config.json
            - /srv/logs/ray-auto-deploy-server:/app/logs
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - jin-proxy
        healthcheck:
            test: ['CMD', 'ping', '-c', '1', '127.0.0.1']
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    jin-proxy:
        external: true
